project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning"
  search:
    type: textbox
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: house
        href: course_information/schedule.qmd
        text: Home
      - icon: file-earmark-pdf
        href: https://chefs-kiss.github.io/ML_J2026/files/ISLP.pdf
        text: ISLP
      - icon: chat-heart
        href: https://mdl.stolaf.edu/course/view.php?id=56310
        text: Moodle
      - icon: github
        href: https://github.com/chefs-kiss/ML_J2026
        text: GitHub
    style: docked
    contents:
    - section: "Course Information"
      contents:
        - href: index.qmd
          text: Home
        - href: course_information/schedule.qmd
          text: Schedule
        - href: https://mdl.stolaf.edu/mod/forum/view.php?id=514243
          text: Moodle Forum
    - section: "Materials"
      contents:
        - href: homework.qmd
          text: Homework
          icon: file-earmark-text
        - href: labs.qmd
          text: Labs
          icon: journal-code
        - href: project.qmd
          text: Project
        - href: slides.qmd
          text: Slides
        - href: articles.qmd
          text: Article Reviews

format:
  html:
    theme: sandstone  #yeti #materia #lux #sandstone #spacelab #vapor   #litera
    #css: styles.css
    toc: true

execute:
  freeze: auto

